fileSuccess:
  javascripts:
    - linecom.jquery.js
    - fixedListHead.js
    - fileNavigation.js
    - toggleDiffRange.js
    - vendor/modplug.min.js
    - vendor/jquery.fracs.js
    - vendor/jquery.outline.js
  stylesheets:
    - vendor/minimap.min.css

fileContentSuccess:
  layout: highlightFile

  stylesheets:
    - vendor/highlight.css
  javascripts:
    - vendor/highlight.pack.js
fileListSuccess:
  javascripts:
    - viewFilesInfo.js
    - toggleDiffRange.js
cimeHelpSuccess:
  has_layout: false
